name: Deploy to Firebase Hosting on Release Push

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, e.g. v1.0.0

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # プロジェクトで使用しているNode.jsのバージョンに合わせてください

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Build SvelteKit app
        run: pnpm build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GEMINI_GENERATED_CHAT_APP }}' # ここはプロジェクトIDに合わせて変更
          projectId: gemini-generated-chat-app # ここはプロジェクトIDに合わせて変更
          channelId: live # または任意のチャンネルID