<script lang="ts">
  import { auth } from '../../lib/firebase';
  import { signInWithEmailAndPassword } from 'firebase/auth';
  import { goto } from '$app/navigation';

  let email = $state('');
  let password = $state('');
  let error: string | null = $state(null);

  async function handleLogin() {
    try {
      await signInWithEmailAndPassword(auth, email, password);
      goto('/');
    } catch (err: any) {
      error = err.message;
    }
  }
</script>

<div class="container">
  <h1>Login</h1>
  <p class="gemini-message">This chat application was generated by Gemini.</p>
  <form onsubmit={e => { e.preventDefault(); handleLogin(); }}>
    <label for="email">Email:</label>
    <input type="email" id="email" bind:value={email} required />

    <label for="password">Password:</label>
    <input type="password" id="password" bind:value={password} required />

    {#if error}
      <p class="error">{error}</p>
    {/if}

    <button type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="/signup">Sign Up</a></p>
</div>

<style>
  .container {
    max-width: 400px;
    margin: 50px auto;
    padding: 30px; /* パディングを増やす */
    background-color: var(--color-surface); /* 背景色を白に */
    border-radius: 8px; /* 角を丸く */
    box-shadow: var(--shadow-lg); /* 影を強調 */
  }
  h1 {
    text-align: center;
    color: var(--color-text); /* テキスト色 */
    margin-bottom: 20px; /* マージン調整 */
  }
  form {
    display: grid;
    grid-template-columns: 1fr;
    gap: 15px;
  }
  label {
    font-weight: 500; /* フォントウェイト調整 */
    color: var(--color-text-light); /* 薄いテキスト色 */
  }
  input[type="email"],
  input[type="password"] {
    padding: 12px;
    border: 1px solid var(--color-border);
    border-radius: 4px;
    font-size: 1em;
    width: 100%;
    background-color: var(--color-background);
    color: var(--color-text);
  }

  input[type="email"]:focus,
  input[type="password"]:focus {
    outline: none;
    border-color: var(--color-primary);
    box-shadow: 0 0 0 3px var(--color-primary-focus);
  }

  button {
    padding: 12px 20px;
    background-color: var(--color-primary);
    color: var(--color-surface);
    border: 1px solid var(--color-primary); /* ボタンの枠線を追加 */
    border-radius: 4px;
    cursor: pointer;
    font-size: 1.1em;
    font-weight: 500;
    transition: background-color 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease;
  }

  button:hover {
    background-color: var(--color-primary-dark);
    border-color: var(--color-primary-dark);
    box-shadow: var(--shadow-md);
  }

  button:focus {
    outline: none;
    box-shadow: 0 0 0 3px var(--color-primary-focus);
  }
  .error {
    color: var(--color-error); /* エラー色 */
    text-align: center;
    margin-top: 10px; /* マージン調整 */
  }
  p {
    text-align: center;
    margin-top: 20px;
    color: var(--color-text-light); /* 薄いテキスト色 */
  }
  a {
    color: var(--color-primary); /* プライマリカラー */
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }

  .gemini-message {
    text-align: center;
    margin-bottom: 20px;
    color: var(--color-text-light); /* 薄いテキスト色 */
    font-style: italic;
    font-size: 0.9em; /* フォントサイズ調整 */
  }
</style>
